### ISSUE TITLE
Issue with create project

### ISSUE THREAD

**Issue by ankitmiyan30** [Prime-Holding/rx_bloc#881]
**rx_bloc_cli create . --project-name test_bloc_app**
Project name: testing_app
Organization name: (com.example) com.tes.dsd
Enable login: (Y/n) No
Enable social logins: (y/N) No
Enable OTP authentication: (y/N) No
Enable Pin Code authentication: (y/N) No
Enabled Multi-Factor Authentication: (y/N) No
Enable change language: (Y/n) No
Enable analytics: (y/N) No
Select realtime communication type: [ none | sse ] (none) none
Enable dev menu: (y/N) No
Enable Patrol integration tests: (y/N) No
Select ci/cd type: [ none | fastlane | github | codemagic ] (fastlane) none
Enabled Profile feature: (Y/n) No
Enable counter showcase: (y/N) No
Enable deeplink: (y/N) No
Enable qr scanner showcase: (y/N) No
Enable widget toolkit showcase: (y/N) No
Unhandled exception:
ProcessException: The system cannot find the file specified.

  Command: flutter create --project-name testing_app --org com.tes.dsd .
#0      _ProcessImpl._start (dart:io-patch/process_patch.dart:402:33)
#1      Process.start (dart:io-patch/process_patch.dart:38:20)
#2      _runNonInteractiveProcess (dart:io-patch/process_patch.dart:579:18)
#3      Process.run (dart:io-patch/process_patch.dart:49:12)
#4      CreateCommand._preGen (package:rx_bloc_cli/src/commands/create_command.dart:70:19)
#5      CreateCommand.run (package:rx_bloc_cli/src/commands/create_command.dart:55:11)
#6      CommandRunner.runCommand (package:args/command_runner.dart:212:27)
#7      RxBlocCommandRunner.runCommand (package:rx_bloc_cli/src/command_runner.dart:61:29)
#8      RxBlocCommandRunner.run (package:rx_bloc_cli/src/command_runner.dart:34:20)
#9      main (file:///C:/Users/AnkitMiyan/AppData/Local/Pub/Cache/hosted/pub.dev/rx_bloc_cli-5.2.0/bin/rx_bloc_cli.dart:6:52)
#10     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:295:33)
#11     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by StanevPrime** [comment]
According to Flutter's specifications, the project name cannot include underscores.
 
With that being said you can use Project name: **testingapp** instead  **testing_app**

**Comment by JaphetSamuel** [comment]
> According to Flutter's specifications, the project name cannot include underscores.
> 
> With that being said you can use Project name: **testingapp** instead **testing_app**

that don't solve this issue for me
